### ISSUE TITLE
Check if we need pyasn1 and cryptography

### ISSUE THREAD

**Issue by kinow** [conda-forge/cylc-flow-feedstock#8]
When I built the first version of the recipe, I went through each error, searched PYPI or Conda Forge for dependencies based on tracebacks. For some reason I added `pyasn1` and `cryptography`.

But I have simply no recollection of why I did that. No idea what error I had. Apologies.

It is important to verify that subcommands work as expected (i.e. `cylc message`, `cylc trigger`, etc.).

See comments: https://github.com/conda-forge/cylc-flow-feedstock/pull/7#discussion_r457176604

**Comment by kinow** [comment]
And if indeed necessary, then let's add a comment explaining why. The other dependencies like the ones used for terminal colors, or GraphQL, protobuf, etc., are easier to guess why they were added, so not necessary to have comments for those.

**Comment by kinow** [comment]
Looks like `pyasn1` and `cryptography` both came with the auto-generator for the recipe. Likely via `python-jose`: https://pypi.org/project/python-jose/

Quite sure we don't have python-jose anymore (it was used for JWT I think?). So we should be OK to remove both dependencies in the next release, after running some tests just to be sure I think.

**Comment by oliver-sanders** [comment]
removed.
